import dynamic from "next/dynamic";
import NavBar from "../../components/NavBar";
import styles from "../../styles/global.module.css";
import { Wallet } from "../../components/Wallet";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className={styles.html} lang="en">
            <body className={styles.root}>
                <Wallet>{children}</Wallet>
            </body>
        </html>
    );
}
